import { createContext, useContext, useState } from "react";

const T = {
  en: {
    appName: "BeanHealth",
    appSubtitle: "Patient Portal",
    appDesc: "Kidney Transplant & ESRD Patient Management",
    dashboard: "Dashboard",
    history: "History",
    prescriptions: "Prescriptions",
    profile: "Profile",
    logout: "Logout",
    signIn: "Sign In",
    register: "Register",
    mrId: "MR ID",
    mrIdPlaceholder: "e.g. MR001",
    password: "Password",
    fullName: "Full Name",
    fathersName: "Father's Name",
    dob: "Date of Birth",
    diagnosis: "Diagnosis",
    confirmPwd: "Confirm",
    demoAccount: "Demo account",
    goodMorning: "Good morning",
    goodAfternoon: "Good afternoon",
    goodEvening: "Good evening",
    recordVitals: "Record Today's Vitals",
    todayMeds: "Today's Medications",
    lastRecorded: "Last recorded",
    record: "Record",
    edit: "Edit",
    adherence: "adherence",
    taken: "taken",
    bloodPressure: "Blood Pressure",
    bodyWeight: "Body Weight",
    bloodGlucose: "Blood Glucose",
    urineOutput: "Urine Output",
    systolic: "SYS",
    diastolic: "DIA",
    vitalsHistory: "Vitals History",
    trackTrends: "Track and review your health trends",
    allVitals: "All Vitals",
    last7: "Last 7 days",
    last14: "Last 14 days",
    last30: "Last 30 days",
    last90: "Last 90 days",
    listView: "List View",
    trends: "Trends",
    noVitals: "No vitals recorded for this period.",
    prescriptionsTitle: "Prescriptions",
    prescriptionHistory: "Prescription history from your doctor",
    noPrescriptions: "No prescriptions yet",
    noPrescriptionsDesc: "Your doctor will add prescriptions once connected.",
    latest: "Latest",
    doctorsNotes: "Doctor's Notes",
    medications: "medications",
    patientProfile: "Patient Profile",
    medicalInfo: "Medical Information",
    personalClinical: "Personal & clinical details on record",
    mrIdLabel: "MR ID",
    fatherNameLabel: "Father's Name",
    dobLabel: "Date of Birth",
    ageLabel: "Age",
    diagnosisLabel: "Diagnosis",
    treatingDoctor: "Treating Doctor",
    doctorConnection: "Doctor Connection",
    connected: "Connected",
    pending: "Pending",
    yearsOld: "Years old",
    registered: "Registered",
    noMedications: "No prescription found. Your doctor will add your prescription.",
    recorded: "Recorded",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    deleteVital: "Delete",
    editVital: "Edit vital",
    vitals: "Vitals",
    takenToday: "taken today",
    tapToRecord: "Tap to record",
    vsYesterday: "vs yesterday",
    viewHistory: "View history",
    morning: "MORNING",
    afternoon: "AFTERNOON",
    night: "NIGHT",
    recordVital: "Record Vital",
    historyTitle: "History",
    list: "List",
    range7: "7d",
    range30: "30d",
    range90: "90d",
    notRecorded: "Not recorded",
    editEntriesFor: "Edit entries for",
    deleteDayTitle: "Delete all entries?",
    deleteDayDesc: "This will permanently remove all vital records for",
    deleteConfirm: "Delete",
    done: "Done",
  },
  ta: {
    appName: "பீன் ஹெல்த்",
    appSubtitle: "நோயாளர் போர்டல்",
    appDesc: "சிறுநீரக மாற்று & ESRD நோயாளர் மேலாண்மை",
    dashboard: "முகப்பு",
    history: "வரலாறு",
    prescriptions: "மருந்து சீட்டு",
    profile: "சுயவிவரம்",
    logout: "வெளியேறு",
    signIn: "உள்நுழைய",
    register: "பதிவு",
    mrId: "MR எண்",
    mrIdPlaceholder: "எ.கா. MR001",
    password: "கடவுச்சொல்",
    fullName: "முழு பெயர்",
    fathersName: "தந்தையின் பெயர்",
    dob: "பிறந்த தேதி",
    diagnosis: "நோய் கண்டறிதல்",
    confirmPwd: "உறுதிப்படுத்து",
    demoAccount: "டெமோ கணக்கு",
    goodMorning: "காலை வணக்கம்",
    goodAfternoon: "மதிய வணக்கம்",
    goodEvening: "மாலை வணக்கம்",
    recordVitals: "இன்றைய உடல் நிலை பதிவு",
    todayMeds: "இன்றைய மருந்துகள்",
    lastRecorded: "கடைசி பதிவு",
    record: "பதிவு செய்",
    edit: "திருத்து",
    adherence: "மருந்து கடைப்பிடிப்பு",
    taken: "எடுத்தது",
    bloodPressure: "இரத்த அழுத்தம்",
    bodyWeight: "உடல் எடை",
    bloodGlucose: "இரத்த சர்க்கரை",
    urineOutput: "சிறுநீர் வெளியீடு",
    systolic: "சிஸ்",
    diastolic: "டயா",
    vitalsHistory: "உடல் நிலை வரலாறு",
    trackTrends: "உங்கள் சுகாதார போக்குகளை கண்காணிக்கவும்",
    allVitals: "அனைத்தும்",
    last7: "கடந்த 7 நாட்கள்",
    last14: "கடந்த 14 நாட்கள்",
    last30: "கடந்த 30 நாட்கள்",
    last90: "கடந்த 90 நாட்கள்",
    listView: "பட்டியல்",
    trends: "போக்குகள்",
    noVitals: "இந்த காலகட்டத்தில் பதிவுகள் இல்லை.",
    prescriptionsTitle: "மருந்து சீட்டுகள்",
    prescriptionHistory: "உங்கள் மருத்துவரின் மருந்து வரலாறு",
    noPrescriptions: "மருந்து சீட்டு இல்லை",
    noPrescriptionsDesc: "இணைக்கப்பட்டதும் மருந்து சீட்டு சேர்க்கப்படும்.",
    latest: "சமீபத்திய",
    doctorsNotes: "மருத்துவரின் குறிப்புகள்",
    medications: "மருந்துகள்",
    patientProfile: "நோயாளர் சுயவிவரம்",
    medicalInfo: "மருத்துவ தகவல்",
    personalClinical: "தனிப்பட்ட & மருத்துவ விவரங்கள்",
    mrIdLabel: "MR எண்",
    fatherNameLabel: "தந்தையின் பெயர்",
    dobLabel: "பிறந்த தேதி",
    ageLabel: "வயது",
    diagnosisLabel: "நோய் கண்டறிதல்",
    treatingDoctor: "சிகிச்சை மருத்துவர்",
    doctorConnection: "மருத்துவர் இணைப்பு",
    connected: "இணைக்கப்பட்டது",
    pending: "நிலுவையில்",
    yearsOld: "வயது",
    registered: "பதிவு",
    noMedications: "மருந்து சீட்டு இல்லை. மருத்துவர் சேர்ப்பார்.",
    recorded: "பதிவு செய்யப்பட்டது",
    saveChanges: "சேமி",
    cancel: "ரத்து",
    deleteVital: "நீக்கு",
    editVital: "திருத்தவும்",
    vitals: "நிலைகள்",
    takenToday: "இன்று எடுத்தது",
    tapToRecord: "பதிவு செய்ய தொடவும்",
    vsYesterday: "நேற்றுடன்",
    viewHistory: "வரலாறு காண்",
    morning: "காலை",
    afternoon: "மதியம்",
    night: "இரவு",
    recordVital: "உடல் நிலை பதிவு",
    historyTitle: "வரலாறு",
    list: "பட்டியல்",
    range7: "7நா",
    range30: "30நா",
    range90: "90நா",
    notRecorded: "பதிவு இல்லை",
    editEntriesFor: "பதிவுகளை திருத்து",
    deleteDayTitle: "அனைத்து பதிவுகளையும் நீக்கவா?",
    deleteDayDesc: "இந்த தேதியின் அனைத்து பதிவுகளும் நிரந்தரமாக நீக்கப்படும்:",
    deleteConfirm: "நீக்கு",
    done: "முடிந்தது",
  },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(
    () => localStorage.getItem("bean_lang") || "en"
  );

  const toggleLang = () => {
    const next = lang === "en" ? "ta" : "en";
    localStorage.setItem("bean_lang", next);
    setLang(next);
  };

  return (
    <LangContext.Provider value={{ lang, t: T[lang], toggleLang }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
