-- Migration: Create reference_drugs table for global medication database
-- Run this in Supabase SQL Editor
-- This version uses BRAND NAMES as primary entries

-- Drop existing table if it exists (clean slate approach)
DROP TABLE IF EXISTS reference_drugs CASCADE;

-- Create the reference_drugs table with brand names as primary
CREATE TABLE reference_drugs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  brand_name TEXT NOT NULL,           -- Primary: The brand name (e.g., "Ciprodac 500")
  generic_name TEXT NOT NULL,         -- Generic/pharmacology name (e.g., "Ciprofloxacin")
  category TEXT NOT NULL,             -- Drug category (e.g., "ANTIBIOTIC")
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- Ensure unique brand names
  UNIQUE(brand_name)
);

-- Create indexes for faster searches
CREATE INDEX idx_reference_drugs_brand ON reference_drugs(brand_name);
CREATE INDEX idx_reference_drugs_generic ON reference_drugs(generic_name);
CREATE INDEX idx_reference_drugs_category ON reference_drugs(category);

-- Enable Row Level Security
ALTER TABLE reference_drugs ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Allow read for authenticated users" ON reference_drugs;
DROP POLICY IF EXISTS "Allow all for service role" ON reference_drugs;

-- Allow all authenticated users to read reference drugs
CREATE POLICY "Allow read for authenticated users" ON reference_drugs
  FOR SELECT TO authenticated USING (true);

-- Allow service role to manage (for admin operations)
CREATE POLICY "Allow all for service role" ON reference_drugs
  FOR ALL TO service_role USING (true);

-- Insert all medications with BRAND NAMES as primary
INSERT INTO reference_drugs (brand_name, generic_name, category) VALUES
-- ANTIBIOTICS
('Ciprodac 500', 'CIPROFLOXACIN', 'ANTIBIOTIC'),
('Ciprodac 250 mg', 'CIPROFLOXACIN', 'ANTIBIOTIC'),
('Vanud 250', 'VANCOMYCIN', 'ANTIBIOTIC'),
('L-Cin-250', 'LEVOFLOXACIN', 'ANTIBIOTIC'),
('Levoquin-500', 'LEVOFLOXACIN', 'ANTIBIOTIC'),
('Utinef SR 100', 'NITROFURANTOIN', 'ANTIBIOTIC'),
('Augpen 625 mg', 'AMOXYCILLIN/CLAVULANATE', 'ANTIBIOTIC'),
('Gifazin 400', 'RIFAXIMIN', 'ANTIBIOTIC'),
('Rifagut 550', 'RIFAXIMIN', 'ANTIBIOTIC'),
('Minolox-100', 'MINOCYCLINE', 'ANTIBIOTIC'),
('Cipli', 'CIPRO+TINIDAZOLE', 'ANTIBIOTIC'),
('IX-TZ', 'CIPRO+TINIDAZOLE', 'ANTIBIOTIC'),
('Farostead', 'FAROPENAM', 'ANTIBIOTIC'),
('Faroart-200', 'FAROPENAM', 'ANTIBIOTIC'),
('Faroight CV-300', 'FAROPENEM+CLAVULANIC', 'ANTIBIOTIC'),
('Bactole 600', 'LINEZOLID', 'ANTIBIOTIC'),
('Megazolid 600', 'LINEZOLID', 'ANTIBIOTIC'),

-- ANALGESICS & ANTI INFLAMMATORY
('Tramadus-P', 'ACETAMINOPHEN+TRAMADOL', 'ANALGESICS'),
('Lox 2% Jelly', 'LIDOCAINE', 'ANALGESICS'),
('Dolonex DT 20', 'PIROXICAM', 'ANALGESICS'),
('Ultra Artho Gel', 'DICLOFENAC GEL', 'ANALGESICS'),

-- ANTISPASMODICS
('Drotader 40', 'DROTAVERINE', 'ANTISPASMODICS'),

-- ANTIPYRETICS & MUSCLE RELAXANT
('Bacfen-5', 'BACLOFEN', 'ANTIPYRETICS'),
('Bacfen-10', 'BACLOFEN', 'ANTIPYRETICS'),
('Aristomol 650', 'PARACETAMOL', 'ANTIPYRETICS'),
('Paracad 500', 'PARACETAMOL', 'ANTIPYRETICS'),
('Myospaz', 'PARACETAMOL+CHLORZOXAZONE', 'ANTIPYRETICS'),

-- ANTI ULCER
('Panon 40', 'PANTOPRAZOLE', 'ANTI ULCER'),
('NV Pan-On D', 'PANTOPRAZOLE+DOMPERIDONE', 'ANTI ULCER'),
('Ulgel', 'MAGALDRATE+SIMETHICONE', 'ANTI ULCER'),
('Ulgel-A', 'MAGALDRATE+OXETACAINE+SIMETHICONE', 'ANTI ULCER'),
('Sucihavar-O', 'SUCRALFATE+OXETACAINE', 'ANTI ULCER'),

-- ANTI EMETICS
('Emitus', 'ONDANSETRON', 'ANTI EMETICS'),
('Vompril', 'ONDANSETRON', 'ANTI EMETICS'),

-- ANTI VIRAL
('Vag 450 mg', 'VALACYCLOVIR', 'ANTI VIRAL'),
('Cmvgel 450', 'VALACYCLOVIR', 'ANTI VIRAL'),

-- LAXATIVE
('Crema-Fin Plus', 'LIQUID PARAFFIN+MILK OF MAGNESIA', 'LAXATIVE'),
('Cremaffin SY', 'LIQUID PARAFFIN+MILK OF MAGNESIA', 'LAXATIVE'),
('Uzupas', 'LACTULOSE', 'LAXATIVE'),
('Dulcoflex Tab', 'BISACODYL', 'LAXATIVE'),
('Prulooz 1 mg', 'PRUCALOPRIDE', 'LAXATIVE'),
('Prulooz 2 mg', 'PRUCALOPRIDE', 'LAXATIVE'),

-- ANTI DIARRHEALS
('Eldoper', 'LOPERAMIDE', 'ANTI DIARRHEALS'),
('Lopamide', 'LOPERAMIDE', 'ANTI DIARRHEALS'),
('Vibact', 'PRE+PROBIOTIC', 'ANTI DIARRHEALS'),
('Econorm Sach', 'PRE+PROBIOTIC', 'ANTI DIARRHEALS'),
('Zedott-100', 'RACECADOTRIL', 'ANTI DIARRHEALS'),
('Redotil Sach', 'RACECADOTRIL', 'ANTI DIARRHEALS'),
('Metrogyl-400', 'METRONIDAZOLE', 'ANTI DIARRHEALS'),

-- ASTHMATIC
('Doxofyl-400', 'DOXOFYLLINE', 'ASTHMATIC'),
('Doxofyl-201', 'DOXOFYLLINE', 'ASTHMATIC'),
('Deriphyllin 150 mg', 'ETOFYLLINE+THEOPHYLLINE', 'ASTHMATIC'),

-- INHALER
('Seroflo 125 Inhaler', 'SALMETEROL+FLUTICASONE', 'INHALER'),
('Budamate Inhaler', 'BUDESONIDE+FORMOTEROL', 'INHALER'),

-- ANTI ALLERGIC
('Levocad', 'LEVOCETIRIZINE', 'ANTI ALLERGIC'),
('Montison LC', 'MONTELUKAST+LEVOCETIRIZINE', 'ANTI ALLERGIC'),
('Allegra-180', 'FEXOFENADINE', 'ANTI ALLERGIC'),
('Fexcel 120', 'FEXOFENADINE', 'ANTI ALLERGIC'),
('Atarax 10', 'HYDROXYZINE', 'ANTI ALLERGIC'),
('Atarax 25', 'HYDROXYZINE', 'ANTI ALLERGIC'),

-- STEROID
('Wysolone 5', 'PREDNISOLONE', 'STEROID'),
('Wysolone 10', 'PREDNISOLONE', 'STEROID'),
('Wysolone 20 mg', 'PREDNISOLONE', 'STEROID'),
('Defstead 6 mg', 'DEFLAZACORT', 'STEROID'),

-- SEDATIVE
('Anxit Plus', 'ALPRAZOLAM+SERTALINE', 'SEDATIVE'),
('Alpracad 0.25', 'ALPRAZOLAM', 'SEDATIVE'),
('Alpracad 0.5', 'ALPRAZOLAM', 'SEDATIVE'),
('Lonazep 0.25', 'CLONAZEPAM', 'SEDATIVE'),
('Lonazep 5', 'CLONAZEPAM', 'SEDATIVE'),
('Petril 0.5', 'CLONAZEPAM', 'SEDATIVE'),
('Petril 1.25', 'CLONAZEPAM', 'SEDATIVE'),
('Ativan 1 mg', 'LORAZEPAM', 'SEDATIVE'),
('Ativan 2 mg', 'LORAZEPAM', 'SEDATIVE'),
('Valium 5', 'DIAZEPAM', 'SEDATIVE'),
('Valium 10 mg', 'DIAZEPAM', 'SEDATIVE'),

-- ANTI CONVULSANTS / EPILEPSY
('Zeptol CR 200', 'CARBAZEPINE', 'ANTI CONVULSANTS'),
('Encorate 300', 'SODIUM VALPORATE', 'ANTI CONVULSANTS'),
('Encorate 500', 'SODIUM VALPORATE', 'ANTI CONVULSANTS'),
('Encorate Chrono 300', 'VALPROIC ACID', 'ANTI CONVULSANTS'),
('Encorate Chrono 500', 'VALPROIC ACID', 'ANTI CONVULSANTS'),
('Eptoin', 'PHENYTOIN SODIUM', 'ANTI CONVULSANTS'),
('Levenue-500', 'LEVETIRACETAM', 'ANTI CONVULSANTS'),
('Inj Leveset', 'LEVETIRACETAM', 'ANTI CONVULSANTS'),
('Levipill 250', 'LEVETIRACETAM', 'ANTI CONVULSANTS'),
('Levipill 750', 'LEVETIRACETAM', 'ANTI CONVULSANTS'),

-- DIURETICS
('Torsenorm 5', 'TORSEMIDE', 'DIURETICS'),
('Torsenorm 10', 'TORSEMIDE', 'DIURETICS'),
('Torsenorm 20', 'TORSEMIDE', 'DIURETICS'),
('Torsenorm 40', 'TORSEMIDE', 'DIURETICS'),
('Inj Botor', 'TORSEMIDE', 'DIURETICS'),
('Torsenorm Plus', 'TORSEMIDE+SPIRONOLACTONE', 'DIURETICS'),
('Aldactone 25', 'SPIRONOLACTONE', 'DIURETICS'),
('Aldactone 50', 'SPIRONOLACTONE', 'DIURETICS'),
('Aldactone 100', 'SPIRONOLACTONE', 'DIURETICS'),
('Matzol 2.5', 'METOLOZONE', 'DIURETICS'),
('Matzol 5', 'METOLOZONE', 'DIURETICS'),
('Lasix 20', 'FUROSEMIDE', 'DIURETICS'),
('Lasix 40', 'FUROSEMIDE', 'DIURETICS'),
('Inj Lasix', 'FUROSEMIDE', 'DIURETICS'),

-- VERTIGO
('Vertin 3', 'BETAHISTINE', 'VERTIGO'),
('Vertin 16', 'BETAHISTINE', 'VERTIGO'),
('Stugeron', 'CINNARIZINE', 'VERTIGO'),

-- HEPATITIS DRUG
('Ursoshift 300', 'URSODEOXYCHOLIC ACID', 'HEPATITIS'),
('Silybon', 'SILYMARIN', 'HEPATITIS'),

-- ANTIANGINAL
('Nicardia 10', 'NIFEDIPINE', 'ANTIANGINAL'),
('Nicardia 20', 'NIFEDIPINE', 'ANTIANGINAL'),
('Nicardia 30', 'NIFEDIPINE', 'ANTIANGINAL'),
('Isolazine', 'ISOSORBIDE+HYDRALAZINE', 'ANTIANGINAL'),
('Isordil 5', 'ISOSORBITATE DINITRATE', 'ANTIANGINAL'),
('Isordil 10', 'ISOSORBITATE DINITRATE', 'ANTIANGINAL'),

-- ALKALINIZING AGENT
('Acicarb 650', 'SODIUM BICARBONATE', 'ALKALINIZING'),
('Acicarb 1 gm', 'SODIUM BICARBONATE', 'ALKALINIZING'),

-- ANTI HAEMORRHAGE
('Inj XA-MC', 'TRANEXAMIC', 'ANTI HAEMORRHAGE'),
('Tab Tranostat', 'TRANEXAMIC', 'ANTI HAEMORRHAGE'),
('Trapic MF', 'TRANEXAMIC+MEFENAMIC ACID', 'ANTI HAEMORRHAGE'),

-- ANTI TUSSIVE / COUGH
('Lupitus', 'LEVOCLOPERASTINE', 'ANTI TUSSIVE'),
('Ascoril', 'TERBUTALINE', 'ANTI TUSSIVE'),
('Ascoril LS', 'TERBUTALINE', 'ANTI TUSSIVE'),
('Mucolite', 'AMBROXOL', 'ANTI TUSSIVE'),
('Alex', 'DEXTROMETHORPHAN+CHLORPHENIRAMINE', 'ANTI TUSSIVE'),
('Codistar DC', 'DEXTROMETHORPHAN+CHLORPHENIRAMINE', 'ANTI TUSSIVE'),

-- B-COMPLEX / VITAMINS
('Benadon', 'PYRIDOXINE', 'VITAMINS'),
('Renal D3', 'CALCITRIOL', 'VITAMINS'),
('Refervit', 'VITAMINS+AMINOACIDS', 'VITAMINS'),
('Inj Refervit', 'VITAMINS+AMINOACIDS', 'VITAMINS'),
('Ferrilip', 'IRON+METHYL COBALAMIN', 'VITAMINS'),
('N-Ciferol Sach', 'CHOLECALCIFEROL', 'VITAMINS'),
('Zincovit Syr', 'VITAMINS+ZINC', 'VITAMINS'),
('Inj Lenziron FCM', 'FERRIC CARBOXY-MALTOSE', 'VITAMINS'),
('Rosome FCM', 'FERRIC CARBOXY-MALTOSE', 'VITAMINS'),
('Inj FC-Iro 100 mg', 'INJ IRON', 'VITAMINS'),
('Mecogen', 'METHYLCOBALAMIN', 'VITAMINS'),

-- EYE/EAR DROPS
('Cipro Eye Drops', 'CIPROFLOXACIN+DEXAMETHASONE', 'EYE EAR DROPS'),
('Oflox D', 'CIPROFLOXACIN+DEXAMETHASONE', 'EYE EAR DROPS'),
('Tropicamet Eye Drops', 'TROPICAMIDE', 'EYE EAR DROPS'),
('Gatiflox', 'GATIFLOXACIN', 'EYE EAR DROPS'),

-- CALCIUM
('Calcial 500', 'CALCIUM+VITAMIN D3', 'CALCIUM'),
('CCVF', 'CALCIUM ACETATE', 'CALCIUM'),
('Phocfi', 'CALCIUM ACETATE', 'CALCIUM'),

-- IRON
('Dexorange Syr', 'IRON+FOLIC ACID', 'IRON'),

-- OINTMENTS
('Betadine 125gm', 'POVIDONE IODINE', 'OINTMENT'),
('Wokadine 15gm', 'POVIDONE IODINE', 'OINTMENT'),
('Mupinet', 'MUPIROCIN', 'OINTMENT'),
('Vole F', 'MICONAZOLE+FLUCANAZOLE', 'OINTMENT'),
('Clonate', 'CLOBETASOL', 'OINTMENT'),

-- ANTI CHOLESTEROL
('Storvas 10', 'ATORVASTATIN', 'ANTI CHOLESTEROL'),
('Storvas 20', 'ATORVASTATIN', 'ANTI CHOLESTEROL'),
('Storvas 40', 'ATORVASTATIN', 'ANTI CHOLESTEROL'),
('Storvas 80', 'ATORVASTATIN', 'ANTI CHOLESTEROL'),
('Storvas CV 10', 'ATORVASTATIN+CLOPIDOGREL', 'ANTI CHOLESTEROL'),
('Storvas CV 20', 'ATORVASTATIN+CLOPIDOGREL', 'ANTI CHOLESTEROL'),
('Storvas CV 40', 'ATORVASTATIN+CLOPIDOGREL', 'ANTI CHOLESTEROL'),
('Rosubeat 10', 'ROSUVASTATIN', 'ANTI CHOLESTEROL'),
('Rosubeat 20', 'ROSUVASTATIN', 'ANTI CHOLESTEROL'),
('Rosubeat CV 10', 'ROSUVAS+CLOPIDOGREL', 'ANTI CHOLESTEROL'),
('Rosubeat CV 20', 'ROSUVAS+CLOPIDOGREL', 'ANTI CHOLESTEROL'),

-- ANTICOAGULANT
('Clopifet 75', 'CLOPIDOGREL', 'ANTICOAGULANT'),
('Clopiode 75', 'CLOPIDOGREL', 'ANTICOAGULANT'),
('Clopifet A 75', 'CLOPIDOGREL+ASPIRIN', 'ANTICOAGULANT'),
('Clopifet A 150', 'CLOPIDOGREL+ASPIRIN', 'ANTICOAGULANT'),
('Acitrom 1', 'NICOUMALONE', 'ANTICOAGULANT'),
('Acitrom 2', 'NICOUMALONE', 'ANTICOAGULANT'),
('Acitrom 3', 'NICOUMALONE', 'ANTICOAGULANT'),
('Acitrom 4', 'NICOUMALONE', 'ANTICOAGULANT'),

-- ANTI HYPERTENSIVES
('Arkap Ess', 'CLONIDINE', 'ANTI HYPERTENSIVES'),
('Px Beta XL 25', 'METAPROLOL', 'ANTI HYPERTENSIVES'),
('Nebistar 2.5', 'NEBIVOLOL', 'ANTI HYPERTENSIVES'),
('Nebistar 5', 'NEBIVOLOL', 'ANTI HYPERTENSIVES'),
('Nebistar 10', 'NEBIVOLOL', 'ANTI HYPERTENSIVES'),
('Telma 20', 'TELMISARTAN', 'ANTI HYPERTENSIVES'),
('Telma 40', 'TELMISARTAN', 'ANTI HYPERTENSIVES'),
('Losacar 25', 'LOSARTAN', 'ANTI HYPERTENSIVES'),
('Losacar 50', 'LOSARTAN', 'ANTI HYPERTENSIVES'),
('Amlong 5', 'AMLODIPINE', 'ANTI HYPERTENSIVES'),
('Amlong 10', 'AMLODIPINE', 'ANTI HYPERTENSIVES'),

-- CARDIO BETA BLOCKERS
('Lalcar ER 10', 'CARVEDILOL', 'BETA BLOCKERS'),
('Lalcar ER 20', 'CARVEDILOL', 'BETA BLOCKERS'),
('Carca 6', 'CARVEDILOL', 'BETA BLOCKERS'),
('Carca 25', 'CARVEDILOL', 'BETA BLOCKERS'),
('Cardivas CR 40', 'CARVEDILOL', 'BETA BLOCKERS'),
('Inderal 10', 'PROPRANOLOL HCL', 'BETA BLOCKERS'),
('Inderal LA 20', 'PROPRANOLOL HCL', 'BETA BLOCKERS'),

-- ACE INHIBITOR
('Zorlim 5 mg', 'RAMIPRIL', 'ACE INHIBITOR'),

-- CARDIOVASCULAR
('Digo', 'DIGOXIN', 'CARDIOVASCULAR'),
('Tachy RA 200', 'AMIODARONE', 'CARDIOVASCULAR'),

-- MISCELLANEOUS
('Fixuric ER 40', 'FEBUXOSTAT', 'MISCELLANEOUS'),
('Febutaz', 'FEBUXOSTAT', 'MISCELLANEOUS'),
('Zycolchin', 'COLCHICIN', 'MISCELLANEOUS'),

-- ANTI DIABETICS
('Glizid 40', 'GLICLAZIDE', 'ANTI DIABETICS'),
('Glizid 80', 'GLICLAZIDE', 'ANTI DIABETICS'),
('Melmet SR', 'METFORMIN', 'ANTI DIABETICS'),
('Istamet 25', 'SITAGLIPTIN+METFORMIN', 'ANTI DIABETICS'),
('Istamet 50', 'SITAGLIPTIN+METFORMIN', 'ANTI DIABETICS'),
('Istamet 50/500', 'SITAGLIPTIN+METFORMIN', 'ANTI DIABETICS'),
('Glizid M 40', 'GLICLAZIDE+METFORMIN', 'ANTI DIABETICS'),
('Glizid M 80', 'GLICLAZIDE+METFORMIN', 'ANTI DIABETICS'),
('Glynase', 'GLUPIZIDE', 'ANTI DIABETICS'),

-- ANTI FUNGAL
('Syscan 200', 'FLUCONAZOLE', 'ANTI FUNGAL'),
('Inflexan', 'FLUCONAZOLE', 'ANTI FUNGAL'),

-- ANTI MALARIAL
('Oh-CQ 200', 'HYDROXYCHLOROQUINE', 'ANTI MALARIAL'),
('HCQ 200', 'HYDROXYCHLOROQUINE', 'ANTI MALARIAL'),
('Inj Falcinil 60', 'ARTESUNATE SULPHA+PYRIMETHAMINE', 'ANTI MALARIAL'),

-- ANTHELMITIC
('Bendex', 'ALBENDAZOLE', 'ANTHELMITIC'),

-- DIGESTIVE ENZYMES
('G. Panase 10K', 'PANCREATIN', 'DIGESTIVE ENZYMES'),
('G. Panase 15K', 'PANCREATIN', 'DIGESTIVE ENZYMES'),

-- PERIPHERAL VASCULAR
('Stiloz 50', 'CILOSTAZOL', 'PERIPHERAL VASCULAR'),
('Stiloz 100', 'CILOSTAZOL', 'PERIPHERAL VASCULAR'),
('Alfoo', 'ALFUZOSIN', 'PERIPHERAL VASCULAR'),

-- DRUGS FOR BPH
('Rapilif 8', 'SILODISIN', 'BPH'),
('Rapilif M', 'SILODISIN+MIRABEGRON', 'BPH'),
('Silofast-M', 'SILODISIN+MIRABEGRON', 'BPH'),
('Dutas-T', 'DUTASTERIDE+TAMSULOCIN', 'BPH'),
('Silofast-D', 'DUTASTERIDE+SILODISIN', 'BPH'),
('Rapilif-D', 'DUTASTERIDE+SILODISIN', 'BPH'),

-- NEUROPATHY
('Gabavel 300', 'GABAPENTIN', 'NEUROPATHY'),
('Veintree 25', 'PREGABALIN', 'NEUROPATHY'),
('Veintree 50', 'PREGABALIN', 'NEUROPATHY'),
('Veintree 75', 'PREGABALIN', 'NEUROPATHY'),
('Veintree NT', 'GABAPENTIN+NORTRIPTYLINE', 'NEUROPATHY'),

-- HORMONES
('Regestrone', 'NORETHINDRONE', 'HORMONES'),

-- ANTI THYROID
('Eltroxin 100 mcg', 'THYROXINE', 'ANTI THYROID'),
('Thyronorm 25', 'THYROXINE', 'ANTI THYROID'),
('Thyronorm 50', 'THYROXINE', 'ANTI THYROID'),
('Thyronorm 75', 'THYROXINE', 'ANTI THYROID'),
('Thyronorm 125', 'THYROXINE', 'ANTI THYROID'),

-- PARKINSONISM
('Pacitane 2mg', 'TRIHEXYPHENIDYL HCL', 'PARKINSONISM'),
('Amantrel', 'AMANTADINE HCL', 'PARKINSONISM'),

-- IMMUNOSUPPRESSANT
('Vingraf 0.25', 'TACROLIMUS', 'IMMUNOSUPPRESSANT'),
('Vingraf 0.5', 'TACROLIMUS', 'IMMUNOSUPPRESSANT'),
('Vingraf 1', 'TACROLIMUS', 'IMMUNOSUPPRESSANT'),
('Vingraf 2 mg', 'TACROLIMUS', 'IMMUNOSUPPRESSANT'),
('Tacrolite 0.25', 'TACROLIMUS', 'IMMUNOSUPPRESSANT'),
('Tacrolite 0.5', 'TACROLIMUS', 'IMMUNOSUPPRESSANT'),
('Tacrolite 1', 'TACROLIMUS', 'IMMUNOSUPPRESSANT'),
('Tacrolite 2 mg', 'TACROLIMUS', 'IMMUNOSUPPRESSANT'),
('Arpimune 25', 'CYCLOSPORINE', 'IMMUNOSUPPRESSANT'),
('Arpimune 50', 'CYCLOSPORINE', 'IMMUNOSUPPRESSANT'),
('Arpimune 100', 'CYCLOSPORINE', 'IMMUNOSUPPRESSANT'),
('MY 360', 'MYCOPHENOLATE MOFETIL', 'IMMUNOSUPPRESSANT'),
('Mystead-500', 'MYCOPHENOLATE MOFETIL', 'IMMUNOSUPPRESSANT'),
('Mofetyl-S-360', 'MYCOPHENOLATE MOFETIL', 'IMMUNOSUPPRESSANT'),

-- POTASSIUM BINDER
('Kaycit', 'CALCIUM POLYSTYRENE', 'POTASSIUM BINDER'),
('K-Rap', 'CALCIUM POLYSTYRENE', 'POTASSIUM BINDER'),

-- PHOSPHATE BINDER
('Sevnate 400', 'SEVELAMER CARBONATE', 'PHOSPHATE BINDER'),

-- POTASSIUM SUPPLEMENT
('Potkclor Syp', 'POTASSIUM CITRATE', 'POTASSIUM SUPPLEMENT'),
('K-Cit Syp', 'POTASSIUM+CITRICACID', 'POTASSIUM SUPPLEMENT'),
('Alkastone Syr', 'POTASSIUM CITRASIUM+MAGNESIUM CITRATE', 'POTASSIUM SUPPLEMENT'),

-- APPETITE
('Aptivate Syr', 'APPETIZER', 'APPETITE'),
('Aristozyme Syr', 'APPETIZER', 'APPETITE'),
('Longifene Syr', 'BUCLIZINE', 'APPETITE'),

-- NEPHROPROTECTIVE
('Alfalog', 'ALPHAKETOANALOGUE', 'NEPHROPROTECTIVE'),
('Ketodan', 'ALPHAKETOANALOGUE', 'NEPHROPROTECTIVE'),
('Renoalfa', 'ALPHAKETOANALOGUE', 'NEPHROPROTECTIVE'),
('Nacshield', 'TAURINE+N-ACETYLCYSTEINE', 'NEPHROPROTECTIVE'),

-- PROBIOTIC
('Lobun', 'STREPTOCOCCUS THERMOPHILUS+LACTOBACILLUS', 'PROBIOTIC'),
('Oxalo', 'OXALOBACTER+LACTOBACILLUS', 'PROBIOTIC'),

-- ANTIBIOTIC INJECTIONS
('Inj Megrrus SB 750 mg', 'MEROPENEM+SULBACTAM', 'ANTIBIOTIC INJECTION'),
('Inj Ceflohem SB-15gm', 'CEFOPERAZONE+SULBACTAM', 'ANTIBIOTIC INJECTION'),
('Inj Ticocin 400 mg', 'TEICOPLANIN', 'ANTIBIOTIC INJECTION'),
('Inj Tazo 2.25', 'PIPERACILLIN+TAZOBACTUM', 'ANTIBIOTIC INJECTION'),
('Tazmen 4.5', 'PIPERACILLIN+TAZOBACTUM', 'ANTIBIOTIC INJECTION'),
('Inj Doxycycline', 'DOXYCYCLINE', 'ANTIBIOTIC INJECTION'),
('T. Lenteclin-LB', 'DOXYCYCLINE', 'ANTIBIOTIC INJECTION'),
('Inj Novapime', 'CEFEPIME', 'ANTIBIOTIC INJECTION'),
('Inj Azget', 'AZTREONAM', 'ANTIBIOTIC INJECTION'),
('Inj Navibact', 'CEFTAZIDIME/AVIBACTAM', 'ANTIBIOTIC INJECTION'),
('Inj Tgkem', 'TIGECYCLINE', 'ANTIBIOTIC INJECTION'),
('Inj Oflox', 'OFLOXACIN', 'ANTIBIOTIC INJECTION'),
('Inj Cilafast', 'IMIPENEM+CILASTATIN', 'ANTIBIOTIC INJECTION'),
('Inj Ornida', 'ORNIDAZOLE', 'ANTIBIOTIC INJECTION'),
('Inj Vanogard 1 gm', 'VANCOMYCIN', 'ANTIBIOTIC INJECTION'),
('Inj Bakton-500', 'AMIKACIN', 'ANTIBIOTIC INJECTION'),
('Inj Amikacin 250', 'AMIKACIN', 'ANTIBIOTIC INJECTION'),
('Inj Bactozone AS-1.5', 'CEFTRIAZONE/SULBACTAM', 'ANTIBIOTIC INJECTION')

ON CONFLICT (brand_name) DO UPDATE SET
  generic_name = EXCLUDED.generic_name,
  category = EXCLUDED.category;

-- Verify insertion
SELECT COUNT(*) as total_drugs FROM reference_drugs;
