-- Seed reference_drugs from INDIAN_DRUG_DATABASE
-- Run in Supabase SQL editor.
INSERT INTO public.reference_drugs
  (brand_name, generic_name, category, atc_code, components, cdsco_schedule, jan_aushadhi, renal_precaution)
VALUES
  ('TORSENORM', 'Torsemide', 'DIURETICS', 'C03CA04', ARRAY['Torsemide'], 'H', TRUE, FALSE),
  ('DYTOR', 'Torsemide', 'DIURETICS', 'C03CA04', ARRAY['Torsemide'], 'H', FALSE, FALSE),
  ('LASIX', 'Furosemide', 'DIURETICS', 'C03CA01', ARRAY['Furosemide'], 'H', TRUE, FALSE),
  ('ALDACTONE', 'Spironolactone', 'DIURETICS', 'C03DA01', ARRAY['Spironolactone'], 'H', TRUE, TRUE),
  ('SEVELAMER', 'Sevelamer Carbonate', 'PHOSPHATE BINDER', 'V03AE02', ARRAY['Sevelamer Carbonate'], 'H', FALSE, FALSE),
  ('PHOSLYRA', 'Calcium Acetate', 'PHOSPHATE BINDER', 'V03AE07', ARRAY['Calcium Acetate'], 'H', FALSE, FALSE),
  ('RENODAPT', 'Mycophenolate Mofetil', 'IMMUNOSUPPRESSANT', 'L04AA06', ARRAY['Mycophenolate Mofetil'], 'H', FALSE, TRUE),
  ('TACROLIMUS', 'Tacrolimus', 'IMMUNOSUPPRESSANT', 'L04AD02', ARRAY['Tacrolimus'], 'H1', FALSE, TRUE),
  ('PROGRAF', 'Tacrolimus', 'IMMUNOSUPPRESSANT', 'L04AD02', ARRAY['Tacrolimus'], 'H1', FALSE, TRUE),
  ('CYCLOPHOSPHAMIDE', 'Cyclophosphamide', 'IMMUNOSUPPRESSANT', 'L01AA01', ARRAY['Cyclophosphamide'], 'H', FALSE, TRUE),
  ('ERYTOP', 'Erythropoietin Alfa', 'HAEMATOLOGICALS', 'B03XA01', ARRAY['Erythropoietin Alfa'], 'H', FALSE, FALSE),
  ('EPREX', 'Epoetin Alfa', 'HAEMATOLOGICALS', 'B03XA01', ARRAY['Epoetin Alfa'], 'H', FALSE, FALSE),
  ('FERONIA', 'Iron Sucrose', 'HAEMATOLOGICALS', 'B03AC', ARRAY['Iron Sucrose'], 'H', FALSE, FALSE),
  ('MONOFER', 'Iron Isomaltoside', 'HAEMATOLOGICALS', 'B03AC', ARRAY['Iron Isomaltoside'], 'H', FALSE, FALSE),
  ('ACICARB', 'Sodium Bicarbonate', 'ELECTROLYTES & ALKALI', 'B05XA02', ARRAY['Sodium Bicarbonate'], 'OTC', TRUE, FALSE),
  ('RENAL_D3', 'Cholecalciferol', 'VITAMINS & MINERALS', 'A11CC05', ARRAY['Cholecalciferol (Vitamin D3)'], 'OTC', TRUE, FALSE),
  ('CALCITRIOL', 'Calcitriol', 'VITAMINS & MINERALS', 'A11CC04', ARRAY['Calcitriol'], 'H', FALSE, FALSE),
  ('ROCALTROL', 'Calcitriol', 'VITAMINS & MINERALS', 'A11CC04', ARRAY['Calcitriol'], 'H', FALSE, FALSE),
  ('CARDACE', 'Ramipril', 'ACE INHIBITOR', 'C09AA05', ARRAY['Ramipril'], 'H', TRUE, TRUE),
  ('ENVAS', 'Enalapril', 'ACE INHIBITOR', 'C09AA02', ARRAY['Enalapril'], 'H', TRUE, TRUE),
  ('LISINOPRIL', 'Lisinopril', 'ACE INHIBITOR', 'C09AA03', ARRAY['Lisinopril'], 'H', TRUE, TRUE),
  ('ZESTRIL', 'Lisinopril', 'ACE INHIBITOR', 'C09AA03', ARRAY['Lisinopril'], 'H', FALSE, TRUE),
  ('PERINDOPRIL', 'Perindopril', 'ACE INHIBITOR', 'C09AA04', ARRAY['Perindopril Erbumine'], 'H', FALSE, TRUE),
  ('LOSARTAN', 'Losartan Potassium', 'ARB', 'C09CA01', ARRAY['Losartan Potassium'], 'H', TRUE, TRUE),
  ('REPACE', 'Losartan Potassium', 'ARB', 'C09CA01', ARRAY['Losartan Potassium'], 'H', FALSE, TRUE),
  ('TELMISARTAN', 'Telmisartan', 'ARB', 'C09CA07', ARRAY['Telmisartan'], 'H', TRUE, TRUE),
  ('TELMA', 'Telmisartan', 'ARB', 'C09CA07', ARRAY['Telmisartan'], 'H', FALSE, TRUE),
  ('TELMIKIND', 'Telmisartan', 'ARB', 'C09CA07', ARRAY['Telmisartan'], 'H', FALSE, TRUE),
  ('OLMY', 'Olmesartan', 'ARB', 'C09CA08', ARRAY['Olmesartan Medoxomil'], 'H', FALSE, TRUE),
  ('OLMIGHTY', 'Olmesartan', 'ARB', 'C09CA08', ARRAY['Olmesartan Medoxomil'], 'H', FALSE, TRUE),
  ('VALTAN', 'Valsartan', 'ARB', 'C09CA03', ARRAY['Valsartan'], 'H', FALSE, TRUE),
  ('DIOVAN', 'Valsartan', 'ARB', 'C09CA03', ARRAY['Valsartan'], 'H', FALSE, TRUE),
  ('AMLIP', 'Amlodipine Besylate', 'CCB', 'C08CA01', ARRAY['Amlodipine Besylate'], 'H', TRUE, FALSE),
  ('AMLONG', 'Amlodipine', 'CCB', 'C08CA01', ARRAY['Amlodipine'], 'H', TRUE, FALSE),
  ('STAMLO', 'Amlodipine', 'CCB', 'C08CA01', ARRAY['Amlodipine'], 'H', FALSE, FALSE),
  ('NIFEDIPINE', 'Nifedipine', 'CCB', 'C08CA05', ARRAY['Nifedipine'], 'H', TRUE, FALSE),
  ('DILZEM', 'Diltiazem', 'CCB', 'C08DB01', ARRAY['Diltiazem Hydrochloride'], 'H', FALSE, FALSE),
  ('ATENOLOL', 'Atenolol', 'BETA BLOCKER', 'C07AB03', ARRAY['Atenolol'], 'H', TRUE, TRUE),
  ('METOPROLOL', 'Metoprolol Succinate', 'BETA BLOCKER', 'C07AB02', ARRAY['Metoprolol Succinate'], 'H', TRUE, FALSE),
  ('BETALOC', 'Metoprolol Succinate', 'BETA BLOCKER', 'C07AB02', ARRAY['Metoprolol Succinate'], 'H', FALSE, FALSE),
  ('CARVEDILOL', 'Carvedilol', 'BETA BLOCKER', 'C07AG02', ARRAY['Carvedilol'], 'H', TRUE, FALSE),
  ('CARCA', 'Carvedilol', 'BETA BLOCKER', 'C07AG02', ARRAY['Carvedilol'], 'H', FALSE, FALSE),
  ('GLYCOMET', 'Metformin Hydrochloride', 'ANTI-DIABETIC', 'A10BA02', ARRAY['Metformin Hydrochloride'], 'H', TRUE, TRUE),
  ('GLUCOPHAGE', 'Metformin Hydrochloride', 'ANTI-DIABETIC', 'A10BA02', ARRAY['Metformin Hydrochloride'], 'H', FALSE, TRUE),
  ('GLIZID', 'Gliclazide', 'ANTI-DIABETIC', 'A10BB09', ARRAY['Gliclazide'], 'H', TRUE, TRUE),
  ('DIAMICRON', 'Gliclazide', 'ANTI-DIABETIC', 'A10BB09', ARRAY['Gliclazide'], 'H', FALSE, TRUE),
  ('AMARYL', 'Glimepiride', 'ANTI-DIABETIC', 'A10BB12', ARRAY['Glimepiride'], 'H', TRUE, TRUE),
  ('GLIMEPIRIDE', 'Glimepiride', 'ANTI-DIABETIC', 'A10BB12', ARRAY['Glimepiride'], 'H', TRUE, TRUE),
  ('JARDIANCE', 'Empagliflozin', 'ANTI-DIABETIC', 'A10BK03', ARRAY['Empagliflozin'], 'H', FALSE, TRUE),
  ('FORXIGA', 'Dapagliflozin', 'ANTI-DIABETIC', 'A10BK01', ARRAY['Dapagliflozin'], 'H', FALSE, TRUE),
  ('SUGARLESS', 'Dapagliflozin', 'ANTI-DIABETIC', 'A10BK01', ARRAY['Dapagliflozin'], 'H', FALSE, TRUE),
  ('INSULIN', 'Insulin Human', 'INSULIN', 'A10AB01', ARRAY['Insulin Human'], 'H', TRUE, FALSE),
  ('LANTUS', 'Insulin Glargine', 'INSULIN', 'A10AE04', ARRAY['Insulin Glargine'], 'H', FALSE, FALSE),
  ('NOVORAPID', 'Insulin Aspart', 'INSULIN', 'A10AB05', ARRAY['Insulin Aspart'], 'H', FALSE, FALSE),
  ('WYSOLONE', 'Prednisolone', 'STEROID', 'H02AB06', ARRAY['Prednisolone'], 'H', TRUE, FALSE),
  ('OMNACORTIL', 'Prednisolone', 'STEROID', 'H02AB06', ARRAY['Prednisolone'], 'H', FALSE, FALSE),
  ('DEXA', 'Dexamethasone', 'STEROID', 'H02AB02', ARRAY['Dexamethasone'], 'H', TRUE, FALSE),
  ('ATORVA', 'Atorvastatin Calcium', 'STATIN', 'C10AA05', ARRAY['Atorvastatin Calcium'], 'H', TRUE, FALSE),
  ('LIPITOR', 'Atorvastatin Calcium', 'STATIN', 'C10AA05', ARRAY['Atorvastatin Calcium'], 'H', FALSE, FALSE),
  ('STORVAS', 'Atorvastatin Calcium', 'STATIN', 'C10AA05', ARRAY['Atorvastatin Calcium'], 'H', FALSE, FALSE),
  ('ROSUVASTATIN', 'Rosuvastatin Calcium', 'STATIN', 'C10AA07', ARRAY['Rosuvastatin Calcium'], 'H', TRUE, FALSE),
  ('ROZUCOR', 'Rosuvastatin Calcium', 'STATIN', 'C10AA07', ARRAY['Rosuvastatin Calcium'], 'H', FALSE, FALSE),
  ('ASPIRIN', 'Aspirin', 'ANTIPLATELET', 'B01AC06', ARRAY['Acetylsalicylic Acid'], 'OTC', TRUE, TRUE),
  ('ECOSPRIN', 'Aspirin', 'ANTIPLATELET', 'B01AC06', ARRAY['Aspirin (Enteric Coated)'], 'OTC', FALSE, TRUE),
  ('CLOPIDOGREL', 'Clopidogrel', 'ANTIPLATELET', 'B01AC04', ARRAY['Clopidogrel Bisulphate'], 'H', TRUE, FALSE),
  ('CLOPILET', 'Clopidogrel', 'ANTIPLATELET', 'B01AC04', ARRAY['Clopidogrel Bisulphate'], 'H', FALSE, FALSE),
  ('CIPLOX', 'Ciprofloxacin', 'ANTIBIOTIC', 'J01MA02', ARRAY['Ciprofloxacin'], 'H', TRUE, TRUE),
  ('CIPROFLOXACIN', 'Ciprofloxacin', 'ANTIBIOTIC', 'J01MA02', ARRAY['Ciprofloxacin'], 'H', TRUE, TRUE),
  ('NITROFURANTOIN', 'Nitrofurantoin', 'ANTIBIOTIC', 'J01XE01', ARRAY['Nitrofurantoin'], 'H', TRUE, TRUE),
  ('FAROART', 'Faropenem Sodium', 'ANTIBIOTIC', 'J01DI01', ARRAY['Faropenem Sodium'], 'H', FALSE, TRUE),
  ('CEFIXIME', 'Cefixime', 'ANTIBIOTIC', 'J01DD08', ARRAY['Cefixime Trihydrate'], 'H', TRUE, TRUE),
  ('AUGMENTIN', 'Amoxicillin + Clavulanic Acid', 'ANTIBIOTIC', 'J01CR02', ARRAY['Amoxicillin', 'Clavulanic Acid'], 'H', FALSE, TRUE),
  ('CLAVAM', 'Amoxicillin + Clavulanic Acid', 'ANTIBIOTIC', 'J01CR02', ARRAY['Amoxicillin', 'Clavulanic Acid'], 'H', FALSE, TRUE),
  ('AZITHROMYCIN', 'Azithromycin', 'ANTIBIOTIC', 'J01FA10', ARRAY['Azithromycin Dihydrate'], 'H', TRUE, FALSE),
  ('AZITHRAL', 'Azithromycin', 'ANTIBIOTIC', 'J01FA10', ARRAY['Azithromycin Dihydrate'], 'H', FALSE, FALSE),
  ('VOVERAN', 'Diclofenac Sodium', 'NSAID', 'M01AB05', ARRAY['Diclofenac Sodium'], 'H', TRUE, TRUE),
  ('KETODAN', 'Ketorolac Tromethamine', 'NSAID', 'M01AB15', ARRAY['Ketorolac Tromethamine'], 'H', FALSE, TRUE),
  ('DOLO', 'Paracetamol', 'ANALGESICS', 'N02BE01', ARRAY['Paracetamol'], 'OTC', TRUE, FALSE),
  ('CALPOL', 'Paracetamol', 'ANALGESICS', 'N02BE01', ARRAY['Paracetamol'], 'OTC', FALSE, FALSE),
  ('PARACETAMOL', 'Paracetamol', 'ANALGESICS', 'N02BE01', ARRAY['Paracetamol'], 'OTC', TRUE, FALSE),
  ('PAN', 'Pantoprazole', 'PROTON PUMP INHIBITOR', 'A02BC02', ARRAY['Pantoprazole Sodium'], 'H', TRUE, FALSE),
  ('PANTOP', 'Pantoprazole', 'PROTON PUMP INHIBITOR', 'A02BC02', ARRAY['Pantoprazole Sodium'], 'H', FALSE, FALSE),
  ('OMEZ', 'Omeprazole', 'PROTON PUMP INHIBITOR', 'A02BC01', ARRAY['Omeprazole'], 'H', TRUE, FALSE),
  ('RANTAC', 'Ranitidine', 'H2 BLOCKER', 'A02BA02', ARRAY['Ranitidine Hydrochloride'], 'H', TRUE, TRUE),
  ('ONDANSETRON', 'Ondansetron', 'ANTIEMETIC', 'A04AA01', ARRAY['Ondansetron Hydrochloride'], 'H', TRUE, FALSE),
  ('EMESET', 'Ondansetron', 'ANTIEMETIC', 'A04AA01', ARRAY['Ondansetron Hydrochloride'], 'H', FALSE, FALSE),
  ('SHELCAL', 'Calcium Carbonate + Vitamin D3', 'VITAMINS & MINERALS', 'A12AA04', ARRAY['Calcium Carbonate', 'Cholecalciferol'], 'OTC', FALSE, FALSE),
  ('CALCIGARD', 'Nifedipine', 'CCB', 'C08CA05', ARRAY['Nifedipine'], 'H', FALSE, FALSE),
  ('FOLIC_ACID', 'Folic Acid', 'VITAMINS & MINERALS', 'B03BB01', ARRAY['Folic Acid'], 'OTC', TRUE, FALSE),
  ('FERROUS_SULPHATE', 'Ferrous Sulphate', 'HAEMATOLOGICALS', 'B03AA07', ARRAY['Ferrous Sulphate'], 'OTC', TRUE, FALSE),
  -- Anticoagulants
  ('APIGAT', 'Apixaban', 'ANTICOAGULANT', 'B01AF02', ARRAY['Apixaban'], 'H', FALSE, TRUE),
  ('APIXABAN', 'Apixaban', 'ANTICOAGULANT', 'B01AF02', ARRAY['Apixaban'], 'H', FALSE, TRUE),
  ('APIXAPIL', 'Apixaban', 'ANTICOAGULANT', 'B01AF02', ARRAY['Apixaban'], 'H', FALSE, TRUE),
  -- Alpha Blockers
  ('ALFOO', 'Alfuzosin Hydrochloride', 'ALPHA BLOCKER', 'G04CA01', ARRAY['Alfuzosin Hydrochloride'], 'H', FALSE, FALSE),
  ('FLOTRAL', 'Alfuzosin Hydrochloride', 'ALPHA BLOCKER', 'G04CA01', ARRAY['Alfuzosin Hydrochloride'], 'H', FALSE, FALSE),
  ('CINTAPRO', 'Prazosin Hydrochloride', 'ALPHA BLOCKER', 'C02CA01', ARRAY['Prazosin Hydrochloride'], 'H', FALSE, FALSE),
  -- Additional CCBs
  ('BENITAB', 'Benidipine Hydrochloride', 'CCB', 'C08CA15', ARRAY['Benidipine Hydrochloride'], 'H', FALSE, FALSE),
  ('CILACAR', 'Cilnidipine', 'CCB', 'C08CA14', ARRAY['Cilnidipine'], 'H', FALSE, FALSE),
  ('ANGIZEM_CD', 'Diltiazem Hydrochloride', 'CCB', 'C08DB01', ARRAY['Diltiazem Hydrochloride'], 'H', FALSE, FALSE),
  ('CARDIVAS_CR', 'Carvedilol', 'BETA BLOCKER', 'C07AG02', ARRAY['Carvedilol'], 'H', FALSE, FALSE),
  ('FLUNDOC', 'Flunarizine Hydrochloride', 'ANTIVERTIGO', 'N07CA03', ARRAY['Flunarizine Hydrochloride'], 'H', FALSE, FALSE),
  -- ACE Inhibitors
  ('COVERSYL', 'Perindopril Erbumine', 'ACE INHIBITOR', 'C09AA04', ARRAY['Perindopril Erbumine'], 'H', FALSE, TRUE),
  -- Cardiac
  ('DIXIN', 'Digoxin', 'CARDIAC GLYCOSIDE', 'C01AA05', ARRAY['Digoxin'], 'H', TRUE, TRUE),
  ('CARDIZINE', 'Trimetazidine Dihydrochloride', 'ANTI-ANGINAL', 'C01EB15', ARRAY['Trimetazidine Dihydrochloride'], 'H', FALSE, TRUE),
  ('ARKAPRESS', 'Clonidine Hydrochloride', 'CENTRALLY ACTING ANTIHYPERTENSIVE', 'C02AC01', ARRAY['Clonidine Hydrochloride'], 'H', FALSE, FALSE),
  -- Immunosuppressants
  ('AZORAN', 'Azathioprine', 'IMMUNOSUPPRESSANT', 'L04AX01', ARRAY['Azathioprine'], 'H', FALSE, TRUE),
  ('CYCLOXAN', 'Cyclophosphamide', 'IMMUNOSUPPRESSANT', 'L01AA01', ARRAY['Cyclophosphamide'], 'H', FALSE, TRUE),
  ('ENDOXEN', 'Cyclophosphamide', 'IMMUNOSUPPRESSANT', 'L01AA01', ARRAY['Cyclophosphamide'], 'H', FALSE, TRUE),
  ('CMVCEL', 'Valganciclovir Hydrochloride', 'ANTIVIRAL', 'J05AB14', ARRAY['Valganciclovir Hydrochloride'], 'H1', FALSE, TRUE),
  -- Steroids / Mineralocorticoids
  ('DEFSTEAD', 'Deflazacort', 'STEROID', 'H02AB13', ARRAY['Deflazacort'], 'H', FALSE, FALSE),
  ('FLUDRICORT', 'Fludrocortisone Acetate', 'MINERALOCORTICOID', 'H02AA02', ARRAY['Fludrocortisone Acetate'], 'H', FALSE, FALSE),
  -- ESA
  ('DARBEJOY', 'Darbepoetin Alfa', 'HAEMATOLOGICALS', 'B03XA02', ARRAY['Darbepoetin Alfa'], 'H', FALSE, FALSE),
  -- Diuretics / MRA
  ('EPTUS', 'Eplerenone', 'DIURETICS', 'C03DA04', ARRAY['Eplerenone'], 'H', FALSE, TRUE),
  ('DIAMOX', 'Acetazolamide', 'DIURETICS', 'S01EC01', ARRAY['Acetazolamide'], 'H', FALSE, TRUE),
  -- Thyroid
  ('ELTROXIN', 'Levothyroxine Sodium', 'THYROID HORMONE', 'H03AA01', ARRAY['Levothyroxine Sodium'], 'H', TRUE, FALSE),
  -- Anti-diabetics
  ('DYNAGLIPT_L', 'Linagliptin', 'ANTI-DIABETIC', 'A10BH05', ARRAY['Linagliptin'], 'H', FALSE, FALSE),
  -- Antigout
  ('FIXURIC_ER', 'Febuxostat', 'ANTIGOUT', 'M04AA03', ARRAY['Febuxostat'], 'H', FALSE, FALSE),
  -- Antifungal
  ('FLUCON', 'Fluconazole', 'ANTIFUNGAL', 'J02AC01', ARRAY['Fluconazole'], 'H', TRUE, TRUE),
  -- Antibiotics
  ('BACTRIM_DS', 'Trimethoprim + Sulfamethoxazole', 'ANTIBIOTIC', 'J01EE01', ARRAY['Trimethoprim', 'Sulfamethoxazole'], 'H', TRUE, TRUE),
  ('CEPHOPRL', 'Cefpodoxime Proxetil', 'ANTIBIOTIC', 'J01DD13', ARRAY['Cefpodoxime Proxetil'], 'H', FALSE, TRUE),
  ('DOXY', 'Doxycycline Hyclate', 'ANTIBIOTIC', 'J01AA02', ARRAY['Doxycycline Hyclate'], 'H', TRUE, FALSE),
  -- Antiepileptics / Neuropsychiatric
  ('ENCORATE_CHRONO', 'Sodium Valproate', 'ANTIEPILEPTIC', 'N03AG01', ARRAY['Sodium Valproate', 'Valproic Acid'], 'H', FALSE, FALSE),
  ('GABANEF', 'Gabapentin', 'ANTICONVULSANT', 'N03AX12', ARRAY['Gabapentin'], 'H', FALSE, TRUE),
  ('GABAWELL', 'Gabapentin', 'ANTICONVULSANT', 'N03AX12', ARRAY['Gabapentin'], 'H', FALSE, TRUE),
  ('ATARAX', 'Hydroxyzine Hydrochloride', 'ANTIHISTAMINE', 'N05BB01', ARRAY['Hydroxyzine Hydrochloride'], 'H', FALSE, FALSE),
  ('DUZELA', 'Duloxetine Hydrochloride', 'ANTIDEPRESSANT', 'N06AX21', ARRAY['Duloxetine Hydrochloride'], 'H', FALSE, TRUE),
  ('BROMOCRIPTIN', 'Bromocriptine Mesylate', 'DOPAMINE AGONIST', 'N04BC01', ARRAY['Bromocriptine Mesylate'], 'H', FALSE, FALSE),
  ('BACFEN', 'Baclofen', 'MUSCLE RELAXANT', 'M03BX01', ARRAY['Baclofen'], 'H', FALSE, TRUE),
  -- Bronchodilators
  ('ABPHYLINE_SR', 'Theophylline', 'BRONCHODILATOR', 'R03DA04', ARRAY['Theophylline'], 'H', FALSE, FALSE),
  ('DOXOBID', 'Doxofylline', 'BRONCHODILATOR', 'R03DA11', ARRAY['Doxofylline'], 'H', FALSE, FALSE),
  -- Antihistamines
  ('FEXCEL', 'Fexofenadine Hydrochloride', 'ANTIHISTAMINE', 'R06AX26', ARRAY['Fexofenadine Hydrochloride'], 'OTC', FALSE, FALSE),
  -- GI
  ('ELDOPER', 'Domperidone', 'ANTIEMETIC', 'A03FA03', ARRAY['Domperidone'], 'H', FALSE, FALSE),
  ('DULCOFLEX', 'Bisacodyl', 'LAXATIVE', 'A06AB02', ARRAY['Bisacodyl'], 'OTC', FALSE, FALSE),
  ('DROTIN', 'Drotaverine Hydrochloride', 'ANTISPASMODIC', 'A03AD02', ARRAY['Drotaverine Hydrochloride'], 'H', FALSE, FALSE),
  ('G_PANASE', 'Pancreatin', 'DIGESTIVE ENZYME', 'A09AA02', ARRAY['Pancreatin'], 'H', FALSE, FALSE),
  -- Urology / PDE5
  ('EDEGRA', 'Sildenafil Citrate', 'PDE5 INHIBITOR', 'G04BE03', ARRAY['Sildenafil Citrate'], 'H', FALSE, FALSE),
  -- Vitamins & Minerals
  ('CADCAL', 'Calcium Carbonate', 'VITAMINS & MINERALS', 'A12AA04', ARRAY['Calcium Carbonate'], 'OTC', FALSE, FALSE),
  ('B_LONG', 'Pyridoxine Hydrochloride', 'VITAMINS & MINERALS', 'A11HA02', ARRAY['Pyridoxine Hydrochloride (Vitamin B6)'], 'OTC', FALSE, FALSE),
  ('ARISTOMOL', 'Paracetamol', 'ANALGESICS', 'N02BE01', ARRAY['Paracetamol'], 'OTC', FALSE, FALSE)
ON CONFLICT (brand_name) DO UPDATE SET
  generic_name     = EXCLUDED.generic_name,
  category         = EXCLUDED.category,
  atc_code         = EXCLUDED.atc_code,
  components       = EXCLUDED.components,
  cdsco_schedule   = EXCLUDED.cdsco_schedule,
  jan_aushadhi     = EXCLUDED.jan_aushadhi,
  renal_precaution = EXCLUDED.renal_precaution,
  updated_at       = now();

-- ─── Batch 2: High-frequency + complete H–Z catalog ─────────────────────────
INSERT INTO public.reference_drugs
  (brand_name, generic_name, category, atc_code, components, cdsco_schedule, jan_aushadhi, renal_precaution)
VALUES
  -- NAC
  ('NACSAVE','N-Acetylcysteine','RENOPROTECTIVE','R05CB01',ARRAY['N-Acetylcysteine'],'H',FALSE,FALSE),
  ('NACSHIELD','N-Acetylcysteine','RENOPROTECTIVE','R05CB01',ARRAY['N-Acetylcysteine'],'H',FALSE,FALSE),
  -- Urinary alkalinizers
  ('UZUPAS','Disodium Hydrogen Citrate','URINARY ALKALINIZER','A12BA01',ARRAY['Disodium Hydrogen Citrate'],'OTC',FALSE,FALSE),
  ('OXALO','Potassium Citrate','URINARY ALKALINIZER','A12BA01',ARRAY['Potassium Citrate'],'H',FALSE,TRUE),
  ('URIKIND','Potassium Citrate','URINARY ALKALINIZER','A12BA01',ARRAY['Potassium Citrate'],'H',FALSE,TRUE),
  ('ALKASTONE_B6','Potassium Magnesium Citrate + Pyridoxine','URINARY ALKALINIZER','A12BA01',ARRAY['Potassium Citrate','Magnesium Citrate','Pyridoxine Hydrochloride'],'OTC',FALSE,TRUE),
  ('CRAMPAC_KM','Potassium Magnesium Citrate','ELECTROLYTES & ALKALI','A12BA01',ARRAY['Potassium Citrate','Magnesium Citrate'],'OTC',FALSE,TRUE),
  ('POTRIDE','Potassium Chloride','ELECTROLYTES & ALKALI','A12BA01',ARRAY['Potassium Chloride'],'H',FALSE,TRUE),
  ('SODIC_EC','Sodium Bicarbonate','ELECTROLYTES & ALKALI','B05XA02',ARRAY['Sodium Bicarbonate (Enteric Coated)'],'OTC',FALSE,FALSE),
  -- Phosphate binders
  ('PHOCEL','Calcium Acetate','PHOSPHATE BINDER','V03AE07',ARRAY['Calcium Acetate'],'H',FALSE,FALSE),
  ('SEVNATE','Sevelamer Carbonate','PHOSPHATE BINDER','V03AE02',ARRAY['Sevelamer Carbonate'],'H',FALSE,FALSE),
  ('ZEROPHOS','Calcium Acetate','PHOSPHATE BINDER','V03AE07',ARRAY['Calcium Acetate'],'H',FALSE,FALSE),
  -- CCBs
  ('LALCAR_ER','Lercanidipine Hydrochloride','CCB','C08CA13',ARRAY['Lercanidipine Hydrochloride'],'H',FALSE,FALSE),
  ('NICARDIA_R','Nifedipine','CCB','C08CA05',ARRAY['Nifedipine'],'H',FALSE,FALSE),
  ('NICARDIA_XL','Nifedipine','CCB','C08CA05',ARRAY['Nifedipine'],'H',FALSE,FALSE),
  -- Alpha blockers / Urology
  ('RAPILIF','Silodosin','ALPHA BLOCKER','G04CA04',ARRAY['Silodosin'],'H',FALSE,FALSE),
  ('SILOMAX','Silodosin','ALPHA BLOCKER','G04CA04',ARRAY['Silodosin'],'H',FALSE,FALSE),
  ('PRAZONIC_XL','Prazosin Hydrochloride','ALPHA BLOCKER','C02CA01',ARRAY['Prazosin Hydrochloride'],'H',FALSE,FALSE),
  ('PRAZOPRESS_XL','Prazosin Hydrochloride','ALPHA BLOCKER','C02CA01',ARRAY['Prazosin Hydrochloride'],'H',FALSE,FALSE),
  ('PRAZOTEZ_SR','Prazosin Hydrochloride','ALPHA BLOCKER','C02CA01',ARRAY['Prazosin Hydrochloride'],'H',FALSE,FALSE),
  -- Urology
  ('MIRBEG','Mirabegron','BETA-3 AGONIST','G04BD12',ARRAY['Mirabegron'],'H',FALSE,TRUE),
  ('MIDOTAB','Midodrine Hydrochloride','VASOPRESSOR','C01CA17',ARRAY['Midodrine Hydrochloride'],'H',FALSE,FALSE),
  ('EDEGRA','Sildenafil Citrate','PDE5 INHIBITOR','G04BE03',ARRAY['Sildenafil Citrate'],'H',FALSE,FALSE),
  -- Anti-diabetic
  ('VOLIBO_R','Voglibose','ANTI-DIABETIC','A10BX13',ARRAY['Voglibose'],'H',FALSE,FALSE),
  ('CELERA_NU','Celecoxib','COX-2 INHIBITOR','M01AH01',ARRAY['Celecoxib'],'H',FALSE,TRUE),
  ('ISTAVEL','Vildagliptin','ANTI-DIABETIC','A10BH02',ARRAY['Vildagliptin'],'H',FALSE,TRUE),
  ('NATRISE','Pioglitazone Hydrochloride','ANTI-DIABETIC','A10BG03',ARRAY['Pioglitazone Hydrochloride'],'H',FALSE,FALSE),
  ('MELMET_SR','Metformin Hydrochloride','ANTI-DIABETIC','A10BA02',ARRAY['Metformin Hydrochloride'],'H',FALSE,TRUE),
  ('RYBELSUS','Semaglutide','ANTI-DIABETIC','A10BJ06',ARRAY['Semaglutide'],'H',FALSE,FALSE),
  ('DYNAGLIPT_L','Linagliptin','ANTI-DIABETIC','A10BH05',ARRAY['Linagliptin'],'H',FALSE,FALSE),
  -- Insulin
  ('H_MIXTARD','Biphasic Insulin Human (30/70)','INSULIN','A10AD01',ARRAY['Insulin Human (Regular)','Insulin Human (NPH)'],'H',FALSE,FALSE),
  ('H_INSULIN','Insulin Human','INSULIN','A10AB01',ARRAY['Insulin Human'],'H',FALSE,FALSE),
  ('EGLUCENT','Biphasic Insulin Aspart (25/75)','INSULIN','A10AD05',ARRAY['Insulin Aspart','Insulin Aspart Protamine'],'H',FALSE,FALSE),
  -- Immunosuppressants
  ('OHCQ','Hydroxychloroquine Sulphate','DMARD','P01BA02',ARRAY['Hydroxychloroquine Sulphate'],'H',FALSE,FALSE),
  ('MY360','Mycophenolate Sodium','IMMUNOSUPPRESSANT','L04AA06',ARRAY['Mycophenolate Sodium'],'H',FALSE,TRUE),
  ('MYSTEAD','Mycophenolate Mofetil','IMMUNOSUPPRESSANT','L04AA06',ARRAY['Mycophenolate Mofetil'],'H',FALSE,TRUE),
  ('TACRORITE','Tacrolimus','IMMUNOSUPPRESSANT','L04AD02',ARRAY['Tacrolimus'],'H1',FALSE,TRUE),
  ('VINGRAF','Tacrolimus','IMMUNOSUPPRESSANT','L04AD02',ARRAY['Tacrolimus'],'H1',FALSE,TRUE),
  ('METHOTREXATE','Methotrexate','DMARD','L01BA01',ARRAY['Methotrexate'],'H',FALSE,TRUE),
  ('HYDROXY_UREA','Hydroxyurea','IMMUNOSUPPRESSANT','L01XX05',ARRAY['Hydroxyurea'],'H',FALSE,TRUE),
  ('SAAZ','Sulfasalazine','DMARD','A07EC01',ARRAY['Sulfasalazine'],'H',FALSE,TRUE),
  -- Beta blockers
  ('NEBISTAR','Nebivolol Hydrochloride','BETA BLOCKER','C07AB12',ARRAY['Nebivolol Hydrochloride'],'H',FALSE,FALSE),
  ('INDEROL','Propranolol Hydrochloride','BETA BLOCKER','C07AA05',ARRAY['Propranolol Hydrochloride'],'H',TRUE,FALSE),
  ('INDEROL_LA','Propranolol Hydrochloride','BETA BLOCKER','C07AA05',ARRAY['Propranolol Hydrochloride'],'H',FALSE,FALSE),
  ('RX_BETA_XL','Metoprolol Succinate','BETA BLOCKER','C07AB02',ARRAY['Metoprolol Succinate'],'H',FALSE,FALSE),
  -- Diuretics
  ('MATZOL','Metolazone','DIURETICS','C03BA08',ARRAY['Metolazone'],'H',FALSE,FALSE),
  ('TORGO','Torsemide','DIURETICS','C03CA04',ARRAY['Torsemide'],'H',FALSE,FALSE),
  -- ARBs
  ('MEGACET','Valsartan','ARB','C09CA03',ARRAY['Valsartan'],'H',FALSE,TRUE),
  ('CRAVIHENZ','Valsartan','ARB','C09CA03',ARRAY['Valsartan'],'H',FALSE,TRUE),
  -- Cardiac
  ('IVABRAD','Ivabradine Hydrochloride','ANTI-ANGINAL','C01EB17',ARRAY['Ivabradine Hydrochloride'],'H',FALSE,FALSE),
  ('ISORDIL','Isosorbide Dinitrate','NITRATE','C01DA08',ARRAY['Isosorbide Dinitrate'],'H',TRUE,FALSE),
  ('NITROCONTIN','Glyceryl Trinitrate','NITRATE','C01DA02',ARRAY['Glyceryl Trinitrate'],'H',FALSE,FALSE),
  ('KORANDIL','Nicorandil','ANTI-ANGINAL','C01DX16',ARRAY['Nicorandil'],'H',FALSE,FALSE),
  ('TICAVIC','Ticagrelor','ANTIPLATELET','B01AC24',ARRAY['Ticagrelor'],'H',FALSE,FALSE),
  ('TRANOSTAT','Tranexamic Acid','ANTIFIBRINOLYTIC','B02AA02',ARRAY['Tranexamic Acid'],'H',FALSE,TRUE),
  ('CLOPIODE','Clopidogrel Bisulphate','ANTIPLATELET','B01AC04',ARRAY['Clopidogrel Bisulphate'],'H',FALSE,FALSE),
  ('RIVAFLOW','Rivaroxaban','ANTICOAGULANT','B01AF01',ARRAY['Rivaroxaban'],'H',FALSE,TRUE),
  ('ROSUVA_GOLD','Rosuvastatin Calcium','STATIN','C10AA07',ARRAY['Rosuvastatin Calcium'],'H',FALSE,FALSE),
  ('ZYCOLCHIN','Colchicine','ANTIGOUT','M04AC01',ARRAY['Colchicine'],'H',FALSE,TRUE),
  -- Neuropsychiatric
  ('LEVIPILL','Levetiracetam','ANTIEPILEPTIC','N03AX14',ARRAY['Levetiracetam'],'H',FALSE,TRUE),
  ('LONAZEP','Clonazepam','ANTIEPILEPTIC','N03AE01',ARRAY['Clonazepam'],'H',FALSE,FALSE),
  ('PETRIL','Clonazepam','ANTIEPILEPTIC','N03AE01',ARRAY['Clonazepam'],'H',FALSE,FALSE),
  ('VALPORATE','Sodium Valproate','ANTIEPILEPTIC','N03AG01',ARRAY['Sodium Valproate'],'H',FALSE,FALSE),
  ('QPIN','Quetiapine Fumarate','ANTIPSYCHOTIC','N05AH04',ARRAY['Quetiapine Fumarate'],'H',FALSE,FALSE),
  ('SERTA','Sertraline Hydrochloride','ANTIDEPRESSANT','N06AB06',ARRAY['Sertraline Hydrochloride'],'H',FALSE,FALSE),
  ('ZOLWING','Zolpidem Tartrate','HYPNOTIC','N05CF02',ARRAY['Zolpidem Tartrate'],'H',FALSE,FALSE),
  ('PRULOOZ','Prucalopride Succinate','PROKINETIC','A03AE04',ARRAY['Prucalopride Succinate'],'H',FALSE,TRUE),
  ('STUGERON','Cinnarizine','ANTIVERTIGO','N07CA02',ARRAY['Cinnarizine'],'H',FALSE,FALSE),
  ('CINNARIZINE','Cinnarizine','ANTIVERTIGO','N07CA02',ARRAY['Cinnarizine'],'H',FALSE,FALSE),
  ('BETHERAN','Betahistine Dihydrochloride','ANTIVERTIGO','N07CA01',ARRAY['Betahistine Dihydrochloride'],'H',FALSE,FALSE),
  ('VERTIN','Betahistine Dihydrochloride','ANTIVERTIGO','N07CA01',ARRAY['Betahistine Dihydrochloride'],'H',FALSE,FALSE),
  ('THYRONORM','Levothyroxine Sodium','THYROID HORMONE','H03AA01',ARRAY['Levothyroxine Sodium'],'H',TRUE,FALSE),
  ('LONGIFENE','Buclizine Hydrochloride','ANTIHISTAMINE','R06AA02',ARRAY['Buclizine Hydrochloride'],'H',FALSE,FALSE),
  ('STERIO','Methylprednisolone','STEROID','H02AB04',ARRAY['Methylprednisolone'],'H',FALSE,FALSE),
  ('SICRIPTIN','Bromocriptine Mesylate','DOPAMINE AGONIST','N04BC01',ARRAY['Bromocriptine Mesylate'],'H',FALSE,FALSE),
  -- Antibiotics
  ('INH','Isoniazid','ANTIBIOTIC','J04AC01',ARRAY['Isoniazid'],'H',TRUE,TRUE),
  ('RIFAMPICIN','Rifampicin','ANTIBIOTIC','J04AB02',ARRAY['Rifampicin'],'H',TRUE,FALSE),
  ('LINEZOLID','Linezolid','ANTIBIOTIC','J01XX08',ARRAY['Linezolid'],'H1',FALSE,FALSE),
  ('MINOZ','Minocycline Hydrochloride','ANTIBIOTIC','J01AA08',ARRAY['Minocycline Hydrochloride'],'H',FALSE,FALSE),
  ('UTINIFT','Nitrofurantoin','ANTIBIOTIC','J01XE01',ARRAY['Nitrofurantoin'],'H',FALSE,TRUE),
  -- Vitamins & Minerals
  ('N_CALCIFEROL','Cholecalciferol','VITAMINS & MINERALS','A11CC05',ARRAY['Cholecalciferol (Vitamin D3)'],'OTC',FALSE,FALSE),
  ('RIBOFLAVIN','Riboflavin','VITAMINS & MINERALS','A11HA04',ARRAY['Riboflavin (Vitamin B2)'],'OTC',FALSE,FALSE),
  ('MAGMAXX','Magnesium Oxide','VITAMINS & MINERALS','A12CC',ARRAY['Magnesium Oxide'],'OTC',FALSE,TRUE),
  ('OMEGAREN','Omega-3 Fatty Acids','VITAMINS & MINERALS','C10AX06',ARRAY['Omega-3 Fatty Acids (EPA + DHA)'],'OTC',FALSE,FALSE),
  ('REFERVIT','Methylcobalamin + Folic Acid + Pyridoxine','VITAMINS & MINERALS','B03BB01',ARRAY['Methylcobalamin','Folic Acid','Pyridoxine Hydrochloride'],'H',FALSE,FALSE),
  ('SHELCAL_HD','Calcium Carbonate + Vitamin D3 + Magnesium','VITAMINS & MINERALS','A12AA04',ARRAY['Calcium Carbonate','Cholecalciferol','Magnesium Oxide'],'OTC',FALSE,FALSE),
  -- GI / Hepatobiliary
  ('UDIGOAT','Ursodeoxycholic Acid','HEPATOBILIARY','A05AA02',ARRAY['Ursodeoxycholic Acid'],'H',FALSE,FALSE),
  ('COLOSPA_R','Mebeverine Hydrochloride','ANTISPASMODIC','A03AA04',ARRAY['Mebeverine Hydrochloride'],'H',FALSE,FALSE),
  ('VIBACT','Bacillus Clausii','PROBIOTIC','A07FA',ARRAY['Bacillus Clausii (Probiotic)'],'OTC',FALSE,FALSE),
  ('PANON','Pantoprazole Sodium','PROTON PUMP INHIBITOR','A02BC02',ARRAY['Pantoprazole Sodium'],'H',FALSE,FALSE),
  ('PANTAPROZOLE','Pantoprazole Sodium','PROTON PUMP INHIBITOR','A02BC02',ARRAY['Pantoprazole Sodium'],'H',FALSE,FALSE),
  ('JUNIOR_LANZOLE','Lansoprazole','PROTON PUMP INHIBITOR','A02BC03',ARRAY['Lansoprazole'],'H',FALSE,FALSE),
  ('SUCRAVAR_O','Sucralfate','GASTROPROTECTIVE','A02BX02',ARRAY['Sucralfate'],'H',FALSE,FALSE),
  -- Previously skipped
  ('LENTICILIN_LB','Amoxicillin + Lactobacillus','ANTIBIOTIC','J01CA04',ARRAY['Amoxicillin','Lactobacillus Sporogenes'],'H',FALSE,TRUE),
  ('ARISTOZYME','Fungal Diastase + Pepsin','DIGESTIVE ENZYME','A09AA',ARRAY['Fungal Diastase','Pepsin'],'OTC',FALSE,FALSE),
  ('APTIVATE','Cyproheptadine Hydrochloride','APPETITE STIMULANT','R06AX02',ARRAY['Cyproheptadine Hydrochloride'],'H',FALSE,FALSE),
  ('KETONANO','Essential Amino Acids + Ketoanalogues','CKD NUTRITIONAL SUPPLEMENT','V06DB',ARRAY['Alpha-Keto Acid Analogues','Essential Amino Acids'],'H',FALSE,FALSE),
  ('RENOALFA','Essential Amino Acids + Ketoanalogues','CKD NUTRITIONAL SUPPLEMENT','V06DB',ARRAY['Alpha-Keto Acid Analogues','Essential Amino Acids'],'H',FALSE,FALSE)
ON CONFLICT (brand_name) DO UPDATE SET
  generic_name     = EXCLUDED.generic_name,
  category         = EXCLUDED.category,
  atc_code         = EXCLUDED.atc_code,
  components       = EXCLUDED.components,
  cdsco_schedule   = EXCLUDED.cdsco_schedule,
  jan_aushadhi     = EXCLUDED.jan_aushadhi,
  renal_precaution = EXCLUDED.renal_precaution,
  updated_at       = now();
